function [jobOutput] = ...
    LogRegSingleLambdaSingleFoldCVFromLoader( ...
        dataLoader, ...
        lambdaIn, ...
        numFolds, ...
        indexFold, ...
        regBias)
    
    lambda = lambdaIn;
    [ Features, Labels ] = dataLoader();
    [ ~, cvErr ] = LogRegSingleLambdaSingleFoldCV( ...
        Features, Labels, lambdaIn, numFolds, indexFold, regBias);
        
    jobOutput = struct('lambda', lambda, 'cvErr', cvErr);
    
end
